spring:
  application:
    name: Todo
  server:
    port: ${PORT:8080}
  profiles:
    active: prod
  main:
    allow-bean-definition-overriding: true
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/todo-app
  #    username: root
  #    password: RahulJoshi
  #    driver-class-name: com.mysql.cj.jdbc.Driver

  #MongoDb Configuration
  data:
    mongodb:
      uri: mongodb+srv://Rahul:RahulJoshi@cluster0.6c4gh.mongodb.net/TodoApp?retryWrites=true&w=majority&appName=Cluster0&connectTimeoutMS=30000&socketTimeoutMS=30000
      database: TodoApp
      auto-index-creation: true


  #HIBERNATE CONFIGURATIONS
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
