spring:
  application:
    name: Todo
  server:
    port: ${PORT:8080}
  profiles:
    active: prod
  main:
    allow-bean-definition-overriding: true
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/todo-app
  #    username: root
  #    password: ${mysqlPass}
  #    driver-class-name: com.mysql.cj.jdbc.Driver

  #MongoDb Configuration
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: TodoApp
      auto-index-creation: true


  #HIBERNATE CONFIGURATIONS
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
